### ISSUE TITLE
Contact email address for external users?

### ISSUE THREAD

**Issue by mirenradia** [bjodom/idc#1]
Hello, I have been given access to this system through being part of a oneAPI CoE.

I wanted to email someone for support/feedback/comments so tried to email slurm-pvc-uat@intel.com but it bounced (presumably because it is an Intel internal-only email address). Please can you provide a contact email address for external users?

**Comment by L30nardoSV** [comment]
The same just happened to me as well. Can you @bjodom please provide any contact email? Thanks!

**Comment by jamesreinders** [comment]
ReadmeIDC@intel.com       Include details - as many as you think might be helpful, screenshots as well.
